#!/bin/sh

LIGHT=/usr/sbin/fh-anjia-ajl33pq0866-light
AUDIO=/usr/sbin/fh-anjia-ajl33pq0866-audio

safe()
{
    "$LIGHT" safe || logger -p daemon.err -t anjia-board         "failed to place illumination outputs in safe state"
    "$AUDIO" safe || logger -p daemon.err -t anjia-board         "failed to mute speaker amplifier"
}

case "${1:-start}" in
    start|stop|restart)
        safe
        ;;
    *)
        echo "usage: $0 {start|stop|restart}" >&2
        exit 2
        ;;
esac
